const data = [
  {
    id: 1,
    abbreviation: "ang",
    name: "Dutch Guilder",
    image: require("../assets/images/nation-icon/ang.png"),
  },
  {
    id: 2,
    abbreviation: "ars",
    name: "Argentine Peso",
    image: require("../assets/images/nation-icon/ars.png"),
  },
  {
    id: 3,
    abbreviation: "aud",
    name: "Australian Dollar",
    image: require("../assets/images/nation-icon/aud.png"),
  },
  {
    id: 4,
    abbreviation: "bam",
    name: "Bosnia-Herzegovina Convertible Mark",
    image: require("../assets/images/nation-icon/bam.png"),
  },
  {
    id: 5,
    abbreviation: "bgn",
    name: "Bulgarian Lev",
    image: require("../assets/images/nation-icon/bgn.png"),
  },
  {
    id: 6,
    abbreviation: "bhd",
    name: "Bahraini Dinar",
    image: require("../assets/images/nation-icon/bhd.png"),
  },
  {
    id: 7,
    abbreviation: "bif",
    name: "Burundian Franc",
    image: require("../assets/images/nation-icon/bif.png"),
  },
  {
    id: 8,
    abbreviation: "bnd",
    name: "Brunei Dollar",
    image: require("../assets/images/nation-icon/bnd.png"),
  },
  {
    id: 9,
    abbreviation: "CAD",
    name: "Canadian Dollar",
    image: require("../assets/images/nation-icon/cad.png"),
  },
  {
    id: 10,
    abbreviation: "chf",
    name: "Swiss Franc",
    image: require("../assets/images/nation-icon/chf.png"),
  },
  {
    id: 11,
    abbreviation: "cny",
    name: "Chinese Yuan",
    image: require("../assets/images/nation-icon/cny.png"),
  },
  {
    id: 12,
    abbreviation: "dkk",
    name: "Danish Krone",
    image: require("../assets/images/nation-icon/dkk.png"),
  },
  {
    id: 13,
    abbreviation: "eur",
    name: "Euro",
    image: require("../assets/images/nation-icon/eur.png"),
  },
  {
    id: 14,
    abbreviation: "gbp",
    name: "British Pound",
    image: require("../assets/images/nation-icon/gbp.png"),
  },
  {
    id: 15,
    abbreviation: "hkd",
    name: "Hong Kong Dollar",
    image: require("../assets/images/nation-icon/hkd.png"),
  },
  {
    id: 16,
    abbreviation: "idr",
    name: "Indonesian Rupiah",
    image: require("../assets/images/nation-icon/idr.png"),
  },
  {
    id: 17,
    abbreviation: "inr",
    name: "Indian Rupee",
    image: require("../assets/images/nation-icon/inr.png"),
  },
  {
    id: 18,
    abbreviation: "jpy",
    name: "Japanese Yen",
    image: require("../assets/images/nation-icon/jpy.png"),
  },
  {
    id: 19,
    abbreviation: "khr",
    name: "Cambodian Riel",
    image: require("../assets/images/nation-icon/khr.png"),
  },
  {
    id: 20,
    abbreviation: "krw",
    name: "South Korean Won",
    image: require("../assets/images/nation-icon/krw.png"),
  },
  {
    id: 21,
    abbreviation: "lak",
    name: "Laotian Kip",
    image: require("../assets/images/nation-icon/lak.png"),
  },
  {
    id: 22,
    abbreviation: "myr",
    name: "Malaysian Ringgit",
    image: require("../assets/images/nation-icon/myr.png"),
  },
  {
    id: 23,
    abbreviation: "nok",
    name: "Norwegian Krone",
    image: require("../assets/images/nation-icon/nok.png"),
  },
  {
    id: 24,
    abbreviation: "nzd",
    name: "New Zealand Dollar",
    image: require("../assets/images/nation-icon/nzd.png"),
  },
  {
    id: 25,
    abbreviation: "php",
    name: "Philippine Peso",
    image: require("../assets/images/nation-icon/php.png"),
  },
  {
    id: 26,
    abbreviation: "pln",
    name: "Polish Zloty",
    image: require("../assets/images/nation-icon/pln.png"),
  },
  {
    id: 27,
    abbreviation: "rub",
    name: "Russian Ruble",
    image: require("../assets/images/nation-icon/rub.png"),
  },
  {
    id: 28,
    abbreviation: "sek",
    name: "Swedish Krona",
    image: require("../assets/images/nation-icon/sek.png"),
  },
  {
    id: 29,
    abbreviation: "sgd",
    name: "Singapore Dollar",
    image: require("../assets/images/nation-icon/sgd.png"),
  },
  {
    id: 30,
    abbreviation: "thb",
    name: "Thai Baht",
    image: require("../assets/images/nation-icon/thb.png"),
  },
  {
    id: 31,
    abbreviation: "twd",
    name: "New Taiwan Dollar",
    image: require("../assets/images/nation-icon/twd.png"),
  },
  {
    id: 32,
    abbreviation: "usd",
    name: "United States Dollar",
    image: require("../assets/images/nation-icon/usd.png"),
  },
  {
    id: 33,
    abbreviation: "vnd",
    name: "Vietnamese Dong",
    image: require("../assets/images/nation-icon/vnd.png"),
  },
];

const Currencies = [...data].sort((a, b) => a.name.localeCompare(b.name));

export default Currencies;
