import { getPlaceHolder } from '@/features/trip/utils/AdaptiveImage'

export default [
  {
    id: 1,
    title: 'Lời mời kết bạn',
    message: 'An Nguyễn đã gửi cho bạn một lời mời kết bạn.',
    type: 'actionable',
    category: 'friends',
    date: '2025-04-04',
    time: '10:30:50',
    sender: 'An Nguyễn',
    senderAvatar: require(getPlaceHolder(50, 50)),
    unread: true,
  },
  {
    id: 2,
    title: 'Chia sẻ vị trí',
    message: 'Minh Trần đang chia sẻ vị trí với bạn.',
    type: 'actionable',
    category: 'locations',
    date: '2025-04-03',
    time: '16:45:50',
    sender: 'Minh Trần',
    senderAvatar: require(getPlaceHolder(50, 50)),
    unread: false,
  },
  {
    id: 3,
    title: 'Chỉnh sửa chuyến đi',
    message: "Hoài Phương đã chỉnh sửa chuyến đi 'Đi Thỉnh Kinh'.",
    type: 'navigable',
    category: 'trips',
    date: '2025-04-02',
    time: '08:20:50',
    sender: 'Hoài Phương',
    senderAvatar: require(getPlaceHolder(50, 50)),
    unread: true,
  },
  {
    id: 4,
    title: 'Sắp đến chuyến đi!',
    message: "Còn 3 ngày nữa là đến chuyến đi 'Đà Lạt mộng mơ'.",
    type: 'navigable',
    category: 'reminders',
    date: '2025-04-01',
    time: '09:00:50',
    sender: 'Hệ thống',
    senderAvatar: require(getPlaceHolder(50, 50)),
    unread: true,
  },
  {
    id: 5,
    title: 'Lịch trình chưa hoàn tất',
    message: 'Bạn còn 2 địa điểm hôm nay chưa tham quan, có muốn dời sang ngày mai không?',
    type: 'navigable',
    category: 'reminders',
    date: '2025-04-01',
    time: '17:15:50',
    sender: 'Hệ thống',
    senderAvatar: require(getPlaceHolder(50, 50)),
    unread: false,
  },
  {
    id: 6,
    title: 'Dự báo thời tiết',
    message: 'Hôm nay có khả năng mưa cao, hãy chuẩn bị áo mưa nhé!',
    type: 'navigable',
    category: 'weather',
    date: '2025-04-04',
    time: '07:30:50',
    sender: 'Hệ thống',
    senderAvatar: require(getPlaceHolder(50, 50)),
    unread: true,
  },
  {
    id: 7,
    title: 'Từ chối lời mời',
    message: 'Thư Vy đã từ chối lời mời đi chơi của bạn.',
    type: 'navigable',
    category: 'friends',
    date: '2025-03-30',
    time: '14:10:50',
    sender: 'Thư Vy',
    senderAvatar: require(getPlaceHolder(50, 50)),
    unread: false,
  },
  {
    id: 8,
    title: 'Lời mời kết bạn',
    message: 'An Nguyễn đã gửi cho bạn một lời mời kết bạn.',
    type: 'actionable',
    category: 'friends',
    date: '2025-04-04',
    time: '10:30:50',
    sender: 'An Nguyễn',
    senderAvatar: require(getPlaceHolder(50, 50)),
    unread: true,
  },
]
